//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_student_question
    {
        public int ex_id { get; set; }
        public int Std_ssn { get; set; }
        public int quest_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Student_answer { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
