//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Systems
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Examination_SystemEntities1 : DbContext
    {
        public Examination_SystemEntities1()
            : base("name=Examination_SystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Exam_student_question> Exam_student_question { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Question_Choices> Question_Choices { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Course> Student_Course { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    
        public virtual ObjectResult<string> course_delete(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("course_delete", idParameter, nameParameter);
        }
    
        public virtual ObjectResult<string> course_insert(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("course_insert", idParameter, nameParameter);
        }
    
        public virtual ObjectResult<course_select_Result> course_select(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<course_select_Result>("course_select", idParameter, nameParameter);
        }
    
        public virtual ObjectResult<string> course_update(Nullable<int> id, Nullable<int> newid, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var newidParameter = newid.HasValue ?
                new ObjectParameter("newid", newid) :
                new ObjectParameter("newid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("course_update", idParameter, newidParameter, nameParameter);
        }
    
        public virtual int delete_dept(string dept_name, Nullable<int> id)
        {
            var dept_nameParameter = dept_name != null ?
                new ObjectParameter("Dept_name", dept_name) :
                new ObjectParameter("Dept_name", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_dept", dept_nameParameter, idParameter);
        }
    
        public virtual int delete_exam(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_exam", idParameter);
        }
    
        public virtual ObjectResult<string> delete_exstdques(Nullable<int> ex_id, Nullable<int> std_ssn, Nullable<int> quest_id)
        {
            var ex_idParameter = ex_id.HasValue ?
                new ObjectParameter("ex_id", ex_id) :
                new ObjectParameter("ex_id", typeof(int));
    
            var std_ssnParameter = std_ssn.HasValue ?
                new ObjectParameter("std_ssn", std_ssn) :
                new ObjectParameter("std_ssn", typeof(int));
    
            var quest_idParameter = quest_id.HasValue ?
                new ObjectParameter("quest_id", quest_id) :
                new ObjectParameter("quest_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("delete_exstdques", ex_idParameter, std_ssnParameter, quest_idParameter);
        }
    
        public virtual int delete_instr(string name, Nullable<int> ssn)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var ssnParameter = ssn.HasValue ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_instr", nameParameter, ssnParameter);
        }
    
        public virtual ObjectResult<string> delete_Instructor_Course(Nullable<int> ins_id, Nullable<int> crs_id)
        {
            var ins_idParameter = ins_id.HasValue ?
                new ObjectParameter("ins_id", ins_id) :
                new ObjectParameter("ins_id", typeof(int));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("delete_Instructor_Course", ins_idParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<string> delete_Student_Course(Nullable<int> crs_Id, Nullable<int> std_Ssn)
        {
            var crs_IdParameter = crs_Id.HasValue ?
                new ObjectParameter("crs_Id", crs_Id) :
                new ObjectParameter("crs_Id", typeof(int));
    
            var std_SsnParameter = std_Ssn.HasValue ?
                new ObjectParameter("std_Ssn", std_Ssn) :
                new ObjectParameter("std_Ssn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("delete_Student_Course", crs_IdParameter, std_SsnParameter);
        }
    
        public virtual int delete_topic(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_topic", idParameter);
        }
    
        public virtual ObjectResult<string> deleteAllChoices(Nullable<int> qustion_id)
        {
            var qustion_idParameter = qustion_id.HasValue ?
                new ObjectParameter("qustion_id", qustion_id) :
                new ObjectParameter("qustion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("deleteAllChoices", qustion_idParameter);
        }
    
        public virtual ObjectResult<string> deleteChoice(Nullable<int> qustion_id, string choice)
        {
            var qustion_idParameter = qustion_id.HasValue ?
                new ObjectParameter("qustion_id", qustion_id) :
                new ObjectParameter("qustion_id", typeof(int));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("Choice", choice) :
                new ObjectParameter("Choice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("deleteChoice", qustion_idParameter, choiceParameter);
        }
    
        public virtual ObjectResult<string> deleteQuestion(Nullable<int> qustion_id)
        {
            var qustion_idParameter = qustion_id.HasValue ?
                new ObjectParameter("qustion_id", qustion_id) :
                new ObjectParameter("qustion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("deleteQuestion", qustion_idParameter);
        }
    
        public virtual ObjectResult<string> Enter_Answers(Nullable<int> exam_id, Nullable<int> std_ssn, string a1, string a2, string a3, string a4, string a5, string a6, string a7, string a8, string a9, string a10)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var std_ssnParameter = std_ssn.HasValue ?
                new ObjectParameter("std_ssn", std_ssn) :
                new ObjectParameter("std_ssn", typeof(int));
    
            var a1Parameter = a1 != null ?
                new ObjectParameter("a1", a1) :
                new ObjectParameter("a1", typeof(string));
    
            var a2Parameter = a2 != null ?
                new ObjectParameter("a2", a2) :
                new ObjectParameter("a2", typeof(string));
    
            var a3Parameter = a3 != null ?
                new ObjectParameter("a3", a3) :
                new ObjectParameter("a3", typeof(string));
    
            var a4Parameter = a4 != null ?
                new ObjectParameter("a4", a4) :
                new ObjectParameter("a4", typeof(string));
    
            var a5Parameter = a5 != null ?
                new ObjectParameter("a5", a5) :
                new ObjectParameter("a5", typeof(string));
    
            var a6Parameter = a6 != null ?
                new ObjectParameter("a6", a6) :
                new ObjectParameter("a6", typeof(string));
    
            var a7Parameter = a7 != null ?
                new ObjectParameter("a7", a7) :
                new ObjectParameter("a7", typeof(string));
    
            var a8Parameter = a8 != null ?
                new ObjectParameter("a8", a8) :
                new ObjectParameter("a8", typeof(string));
    
            var a9Parameter = a9 != null ?
                new ObjectParameter("a9", a9) :
                new ObjectParameter("a9", typeof(string));
    
            var a10Parameter = a10 != null ?
                new ObjectParameter("a10", a10) :
                new ObjectParameter("a10", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Enter_Answers", exam_idParameter, std_ssnParameter, a1Parameter, a2Parameter, a3Parameter, a4Parameter, a5Parameter, a6Parameter, a7Parameter, a8Parameter, a9Parameter, a10Parameter);
        }
    
        public virtual ObjectResult<string> Exam_Correction(Nullable<int> exam_id, Nullable<int> st_id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var st_idParameter = st_id.HasValue ?
                new ObjectParameter("st_id", st_id) :
                new ObjectParameter("st_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Exam_Correction", exam_idParameter, st_idParameter);
        }
    
        public virtual ObjectResult<string> Exam_Generation(Nullable<int> std_ssn, string crs_name, Nullable<int> t_f, Nullable<int> choice)
        {
            var std_ssnParameter = std_ssn.HasValue ?
                new ObjectParameter("std_ssn", std_ssn) :
                new ObjectParameter("std_ssn", typeof(int));
    
            var crs_nameParameter = crs_name != null ?
                new ObjectParameter("crs_name", crs_name) :
                new ObjectParameter("crs_name", typeof(string));
    
            var t_fParameter = t_f.HasValue ?
                new ObjectParameter("t_f", t_f) :
                new ObjectParameter("t_f", typeof(int));
    
            var choiceParameter = choice.HasValue ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Exam_Generation", std_ssnParameter, crs_nameParameter, t_fParameter, choiceParameter);
        }
    
        public virtual ObjectResult<string> ins_topic(string name, Nullable<int> crs_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ins_topic", nameParameter, crs_idParameter);
        }
    
        public virtual int insert_dept(Nullable<int> id, string dept_name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dept_nameParameter = dept_name != null ?
                new ObjectParameter("Dept_name", dept_name) :
                new ObjectParameter("Dept_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_dept", idParameter, dept_nameParameter);
        }
    
        public virtual ObjectResult<string> insert_exam(Nullable<int> duration, Nullable<int> crs_id)
        {
            var durationParameter = duration.HasValue ?
                new ObjectParameter("duration", duration) :
                new ObjectParameter("duration", typeof(int));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insert_exam", durationParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<string> insert_exstdques(Nullable<int> ex_id, Nullable<int> std_ssn, Nullable<int> quest_id, string std_answer)
        {
            var ex_idParameter = ex_id.HasValue ?
                new ObjectParameter("ex_id", ex_id) :
                new ObjectParameter("ex_id", typeof(int));
    
            var std_ssnParameter = std_ssn.HasValue ?
                new ObjectParameter("std_ssn", std_ssn) :
                new ObjectParameter("std_ssn", typeof(int));
    
            var quest_idParameter = quest_id.HasValue ?
                new ObjectParameter("quest_id", quest_id) :
                new ObjectParameter("quest_id", typeof(int));
    
            var std_answerParameter = std_answer != null ?
                new ObjectParameter("std_answer", std_answer) :
                new ObjectParameter("std_answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insert_exstdques", ex_idParameter, std_ssnParameter, quest_idParameter, std_answerParameter);
        }
    
        public virtual int insert_instr(Nullable<int> id, string name, Nullable<int> salary, string email, Nullable<System.DateTime> bday, Nullable<int> dept_id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var bdayParameter = bday.HasValue ?
                new ObjectParameter("bday", bday) :
                new ObjectParameter("bday", typeof(System.DateTime));
    
            var dept_idParameter = dept_id.HasValue ?
                new ObjectParameter("dept_id", dept_id) :
                new ObjectParameter("dept_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_instr", idParameter, nameParameter, salaryParameter, emailParameter, bdayParameter, dept_idParameter);
        }
    
        public virtual ObjectResult<string> insert_Instructor_Course(Nullable<int> ins_id, Nullable<int> crs_id)
        {
            var ins_idParameter = ins_id.HasValue ?
                new ObjectParameter("ins_id", ins_id) :
                new ObjectParameter("ins_id", typeof(int));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insert_Instructor_Course", ins_idParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<string> insert_Student_Course(Nullable<int> crs_Id, Nullable<int> std_Ssn)
        {
            var crs_IdParameter = crs_Id.HasValue ?
                new ObjectParameter("crs_Id", crs_Id) :
                new ObjectParameter("crs_Id", typeof(int));
    
            var std_SsnParameter = std_Ssn.HasValue ?
                new ObjectParameter("std_Ssn", std_Ssn) :
                new ObjectParameter("std_Ssn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insert_Student_Course", crs_IdParameter, std_SsnParameter);
        }
    
        public virtual ObjectResult<string> insertChoice(Nullable<int> q_id, string choice)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insertChoice", q_idParameter, choiceParameter);
        }
    
        public virtual ObjectResult<string> insertQuestion(string title, string type, string model_Ans, Nullable<int> crs_ID, Nullable<int> grade)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var model_AnsParameter = model_Ans != null ?
                new ObjectParameter("model_Ans", model_Ans) :
                new ObjectParameter("model_Ans", typeof(string));
    
            var crs_IDParameter = crs_ID.HasValue ?
                new ObjectParameter("crs_ID", crs_ID) :
                new ObjectParameter("crs_ID", typeof(int));
    
            var gradeParameter = grade.HasValue ?
                new ObjectParameter("grade", grade) :
                new ObjectParameter("grade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insertQuestion", titleParameter, typeParameter, model_AnsParameter, crs_IDParameter, gradeParameter);
        }
    
        public virtual ObjectResult<select_exam_Result> select_exam(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_exam_Result>("select_exam", idParameter);
        }
    
        public virtual ObjectResult<select_exstdques_Result> select_exstdques(Nullable<int> ex_id, Nullable<int> std_id, Nullable<int> quest_id)
        {
            var ex_idParameter = ex_id.HasValue ?
                new ObjectParameter("ex_id", ex_id) :
                new ObjectParameter("ex_id", typeof(int));
    
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var quest_idParameter = quest_id.HasValue ?
                new ObjectParameter("quest_id", quest_id) :
                new ObjectParameter("quest_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_exstdques_Result>("select_exstdques", ex_idParameter, std_idParameter, quest_idParameter);
        }
    
        public virtual ObjectResult<select_Instructor_Course_Result> select_Instructor_Course(Nullable<int> ins_id, Nullable<int> crs_id)
        {
            var ins_idParameter = ins_id.HasValue ?
                new ObjectParameter("ins_id", ins_id) :
                new ObjectParameter("ins_id", typeof(int));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_Instructor_Course_Result>("select_Instructor_Course", ins_idParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<select_Student_Course_Result> select_Student_Course(Nullable<int> crs_id, Nullable<int> std_ssn)
        {
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            var std_ssnParameter = std_ssn.HasValue ?
                new ObjectParameter("std_ssn", std_ssn) :
                new ObjectParameter("std_ssn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_Student_Course_Result>("select_Student_Course", crs_idParameter, std_ssnParameter);
        }
    
        public virtual ObjectResult<select_topic_Result> select_topic(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_topic_Result>("select_topic", idParameter, nameParameter);
        }
    
        public virtual ObjectResult<selectChoice_Result> selectChoice(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectChoice_Result>("selectChoice", idParameter);
        }
    
        public virtual ObjectResult<selectQuestion_Result> selectQuestion(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectQuestion_Result>("selectQuestion", idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> student_delete(Nullable<int> ssn)
        {
            var ssnParameter = ssn.HasValue ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("student_delete", ssnParameter);
        }
    
        public virtual ObjectResult<string> student_Insert(Nullable<int> ssn, string fname, string lname, Nullable<System.DateTime> bday, string address, string email, Nullable<int> deptid)
        {
            var ssnParameter = ssn.HasValue ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(int));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var bdayParameter = bday.HasValue ?
                new ObjectParameter("Bday", bday) :
                new ObjectParameter("Bday", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("student_Insert", ssnParameter, fnameParameter, lnameParameter, bdayParameter, addressParameter, emailParameter, deptidParameter);
        }
    
        public virtual ObjectResult<student_select_Result> student_select(Nullable<int> ssn, string fname, Nullable<int> deptid)
        {
            var ssnParameter = ssn.HasValue ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(int));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<student_select_Result>("student_select", ssnParameter, fnameParameter, deptidParameter);
        }
    
        public virtual ObjectResult<string> student_Update(Nullable<int> ssn, Nullable<int> newssn, string fname, string lname, Nullable<System.DateTime> bday, string address, string email, Nullable<int> deptid)
        {
            var ssnParameter = ssn.HasValue ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(int));
    
            var newssnParameter = newssn.HasValue ?
                new ObjectParameter("newssn", newssn) :
                new ObjectParameter("newssn", typeof(int));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var bdayParameter = bday.HasValue ?
                new ObjectParameter("Bday", bday) :
                new ObjectParameter("Bday", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("student_Update", ssnParameter, newssnParameter, fnameParameter, lnameParameter, bdayParameter, addressParameter, emailParameter, deptidParameter);
        }
    
        public virtual int update_dept(Nullable<int> id, string dept_name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dept_nameParameter = dept_name != null ?
                new ObjectParameter("Dept_name", dept_name) :
                new ObjectParameter("Dept_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_dept", idParameter, dept_nameParameter);
        }
    
        public virtual ObjectResult<string> update_exam(Nullable<int> id, Nullable<int> time, Nullable<int> crsid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(int));
    
            var crsidParameter = crsid.HasValue ?
                new ObjectParameter("crsid", crsid) :
                new ObjectParameter("crsid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("update_exam", idParameter, timeParameter, crsidParameter);
        }
    
        public virtual ObjectResult<string> update_exstdques(Nullable<int> ex_id, Nullable<int> std_ssn, Nullable<int> quest_id, Nullable<System.DateTime> date, string std_answer)
        {
            var ex_idParameter = ex_id.HasValue ?
                new ObjectParameter("ex_id", ex_id) :
                new ObjectParameter("ex_id", typeof(int));
    
            var std_ssnParameter = std_ssn.HasValue ?
                new ObjectParameter("std_ssn", std_ssn) :
                new ObjectParameter("std_ssn", typeof(int));
    
            var quest_idParameter = quest_id.HasValue ?
                new ObjectParameter("quest_id", quest_id) :
                new ObjectParameter("quest_id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var std_answerParameter = std_answer != null ?
                new ObjectParameter("std_answer", std_answer) :
                new ObjectParameter("std_answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("update_exstdques", ex_idParameter, std_ssnParameter, quest_idParameter, dateParameter, std_answerParameter);
        }
    
        public virtual int update_instr(Nullable<int> ssn, string name, Nullable<int> dept_id, string update_type)
        {
            var ssnParameter = ssn.HasValue ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dept_idParameter = dept_id.HasValue ?
                new ObjectParameter("dept_id", dept_id) :
                new ObjectParameter("dept_id", typeof(int));
    
            var update_typeParameter = update_type != null ?
                new ObjectParameter("update_type", update_type) :
                new ObjectParameter("update_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_instr", ssnParameter, nameParameter, dept_idParameter, update_typeParameter);
        }
    
        public virtual ObjectResult<string> update_Instructor_Course(Nullable<int> crs_id, Nullable<int> ins_id, Nullable<int> ins_newId, Nullable<int> crs_newId)
        {
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            var ins_idParameter = ins_id.HasValue ?
                new ObjectParameter("ins_id", ins_id) :
                new ObjectParameter("ins_id", typeof(int));
    
            var ins_newIdParameter = ins_newId.HasValue ?
                new ObjectParameter("ins_newId", ins_newId) :
                new ObjectParameter("ins_newId", typeof(int));
    
            var crs_newIdParameter = crs_newId.HasValue ?
                new ObjectParameter("crs_newId", crs_newId) :
                new ObjectParameter("crs_newId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("update_Instructor_Course", crs_idParameter, ins_idParameter, ins_newIdParameter, crs_newIdParameter);
        }
    
        public virtual ObjectResult<string> update_Student_Course(Nullable<int> crs_id, Nullable<int> std_ssn, Nullable<int> crs_newId, Nullable<int> std_newId)
        {
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            var std_ssnParameter = std_ssn.HasValue ?
                new ObjectParameter("std_ssn", std_ssn) :
                new ObjectParameter("std_ssn", typeof(int));
    
            var crs_newIdParameter = crs_newId.HasValue ?
                new ObjectParameter("crs_newId", crs_newId) :
                new ObjectParameter("crs_newId", typeof(int));
    
            var std_newIdParameter = std_newId.HasValue ?
                new ObjectParameter("std_newId", std_newId) :
                new ObjectParameter("std_newId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("update_Student_Course", crs_idParameter, std_ssnParameter, crs_newIdParameter, std_newIdParameter);
        }
    
        public virtual ObjectResult<string> update_topic(Nullable<int> id, string name, Nullable<int> crs_id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("update_topic", idParameter, nameParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<string> UpdateChoice(Nullable<int> q_id, string choice, string newChoice)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            var choiceParameter = choice != null ?
                new ObjectParameter("choice", choice) :
                new ObjectParameter("choice", typeof(string));
    
            var newChoiceParameter = newChoice != null ?
                new ObjectParameter("newChoice", newChoice) :
                new ObjectParameter("newChoice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UpdateChoice", q_idParameter, choiceParameter, newChoiceParameter);
        }
    
        public virtual ObjectResult<string> updateQuestion(Nullable<int> qustion_id, string model_answer, string title, Nullable<int> grade, string type, Nullable<int> course_id)
        {
            var qustion_idParameter = qustion_id.HasValue ?
                new ObjectParameter("qustion_id", qustion_id) :
                new ObjectParameter("qustion_id", typeof(int));
    
            var model_answerParameter = model_answer != null ?
                new ObjectParameter("model_answer", model_answer) :
                new ObjectParameter("model_answer", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var gradeParameter = grade.HasValue ?
                new ObjectParameter("grade", grade) :
                new ObjectParameter("grade", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("updateQuestion", qustion_idParameter, model_answerParameter, titleParameter, gradeParameter, typeParameter, course_idParameter);
        }
    
        public virtual ObjectResult<view_depert_Result> view_depert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<view_depert_Result>("view_depert");
        }
    
        public virtual int view_instructor(string col, string cond)
        {
            var colParameter = col != null ?
                new ObjectParameter("col", col) :
                new ObjectParameter("col", typeof(string));
    
            var condParameter = cond != null ?
                new ObjectParameter("cond", cond) :
                new ObjectParameter("cond", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("view_instructor", colParameter, condParameter);
        }
    }
}
