//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Course
    {
        public int Crs_id { get; set; }
        public int Std_ssn { get; set; }
        public Nullable<int> grade { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
