//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> Crs_id { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
